### ISSUE TITLE
Laravel 9 - Class "Illuminate\Mail\Transport\Transport" not found.

### ISSUE THREAD

**Issue by tbz92** [hafael/azure-mailer-driver#1]
in laravel 9 I get error:
Class "Illuminate\Mail\Transport\Transport" not found.

Can anyone please guide?

**Comment by hafael** [comment]
"One of the largest changes in Laravel 9.x is the transition from SwiftMailer, which is no longer maintained as of December 2021, to Symfony Mailer."
[Laravel 9.x Upgrade Guide](https://laravel.com/docs/9.x/upgrade#symfony-mailer)

I will be working on the solution in the next few hours. Thanks for the feedback.

**Comment by hafael** [comment]
Please check the new release [v0.2.0](https://github.com/hafael/azure-mailer-driver/releases/tag/v0.2.0).
