### ISSUE TITLE
Add help for projects that requires "minimum-stability": "stable"

### ISSUE THREAD

**Issue by olskaw** [hafael/azure-mailer-driver#11]
In a project with minimum-stability: stable (which is the default stability of a new Laravel project)

`composer require hafael/azure-mailer-driver` is not enough to install the **latest v0.3.0**. Composer will **fallback to v0.2.2**.

The problem is, that the dependend package symfony/azure-mailer has currently no stable version.
https://github.com/hafael/azure-mailer-driver/blob/e793d5650802127f2ed89f21cc409508939cec7c/composer.json#L11

When I try to explicit install v0.3.0 this happens:
```
composer require hafael/azure-mailer-driver:v0.3.0
./composer.json has been updated
Running composer update hafael/azure-mailer-driver
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires hafael/azure-mailer-driver v0.3.0 -> satisfiable by hafael/azure-mailer-driver[v0.3.0].
    - hafael/azure-mailer-driver v0.3.0 requires symfony/azure-mailer ^7.0 -> found symfony/azure-mailer[7.1.x-dev] but it does not match your minimum-stability.
```

**Solution which can be documented in the README.md**
Allow unstable version of symfony/azure-mailer first:
`composer require symfony/azure-mailer:@dev`
Now its fine to run
`composer require hafael/azure-mailer-driver`
which install v0.3.0

But I get one more problem at runtime during a mail send:
```
You cannot use \"Symfony\\Component\\Mailer\\Transport\\AbstractHttpTransport\" as the HttpClient component is not installed. Try running \"composer require symfony/http-client\
```
So yes, I have to
`composer require symfony/http-client`
And now it works. I think this could also part of your README.md.

**Comment by hafael** [comment]
Resolved at latest stable version.
