### ISSUE TITLE
Emails Not Sending - 202 Status

### ISSUE THREAD

**Issue by drmmr763** [hafael/azure-mailer-driver#2]
Hello

Excited to try to make use of this in my app. I am running into a few small problems sending emails successfully I'm not sure if I'm doing something wrong or if there's something else going on. 

1. I have a custom email domain I am sending through. It is fully verified / DKIM / SPF. It is also provisioned to the Communication Service instance I am trying to use. I think this is all set up correctly. 
2. I did have some issues with selecting the right API version in the .env. I am now running on `2023-03-31`. (Just a note your docs default the .env config to the 2021 version which had a ton of different errors. 
3. Package version is `.0.2.0`
4. I have verified my senderAddress matches what I have configured in azure for the domain as well. 

I am currently not getting any exceptions thrown when I send an email:

```
public function handle()
    {
        $user = User::where('id', '=', 1)->firstOrFail();
        try {
            Mail::to($user)->send(new \App\Mail\TestEmail());
        } catch (\Symfony\Component\Mailer\Exception\HttpTransportException $exception) {
            $this->error($exception->getMessage());
            // $this->error($exception->getResponse()->getContent());
            $this->error(dd($exception->getResponse()->getInfo()));
            $this->error($exception->getResponse()->getStatusCode());
            // throw $exception;
        } catch (\Symfony\Component\HttpClient\Exception\ClientException $exception) {
            $this->error($exception->getMessage());
            // $this->error($exception->getResponse()->getContent());
            $this->error(dd($exception->getResponse()->getInfo()));
            $this->error($exception->getResponse()->getStatusCode());
            // throw $exception;
        }
        $this->output->success("Sent!");
    }
``` 

However I do not receieve the email, and when I review the logs in azure I do see some evidence that the api calls are making it. When I dump the api request response I get:

```
"{"id":"da7dd26f77b92398ee7867995788dfaa","status":"Running","error":null}"
202
array:9 [
```

So status running and response code 202 seem right. But again, no email being sent out. When I test with the azure CLI:

```
az communication email send --sender "DoNotReply@replaced-this.net" --subject "Contoso Update" --to "myemail@hello.com" --text "Hello valued client. There is an update." --connection-string "xxx"
{
  "error": null,
  "id": "264c8e46-596b-49ed-84ad-63f42dbd2378",
  "status": "Succeeded"
}
```

I get an immediate status succeded. And I do receive the email. 

Any ideas on what to check here? I would really love to use this driver but I don't seem to be able to figure out what I'm missing and why its not sending.

**Comment by drmmr763** [comment]
I did some work and set up the call to the status endpoint. Now I am able to see a real failure:

GET  /emails/operations/{messageID}?api-version=2023-03-31

```
{"id":"4344398e571d1381b475834cf190fa28","status":"Failed","error":{"code":"OperationFailed","message":"Unable to deliver email at this point. ","target":null,"details":null,"innererror":null}}
```

No additional details as to why. Once again hoping for ideas. I opened a ticket with azure as well.

**Comment by hafael** [comment]
Hi Chad! 

Glad for your interest and constructive feedback. I hope I can help you with this configuration, so let's go!

Standard API version
Thanks for the warning, I will correct this point.

About the HTTP 202 response
By default, the response from the Azure Mail Submission Service returns a code 202. This means that your message is accepted and will be processed asynchronously. This should always be the correct answer whether your message is properly delivered or not, as indicated in the API documentation at https://learn.microsoft.com/en-us/rest/api/communication/email/send?tabs= HTTP#response

About message non-delivery error
I reproduced your code instructions and I was able to conclude that the factor responsible for the non-delivery of the message is the header "operation-id" which has as value the GUID generated for the message. In the current code, this identifier is being sent in a string without hyphens, and this format, although accepted by the validator, produces this failure.

I am already publishing a version that corrects these points. Thank you very much for your feedback and collaboration. Please let me know if it worked.

**Comment by drmmr763** [comment]
Thanks for getting back to me @hafael  I will test your bug fix right away. Very much appreciate you identifying the issue.

**Comment by drmmr763** [comment]
Immediate success! Thank you!
