### ISSUE TITLE
Error SSL Symfony: SSL operation failed with code 1. OpenSSL Error messages:\nerror:1416F086:SS

### ISSUE THREAD

**Issue by FuriosoJack** [hafael/azure-mailer-driver#4]
Hello, thank you for your package, it has been of great help to me, however I am presenting an error when the email is sent, I was able to resolve the error and finally discovered that it is an SSL error. The solution that has worked for me is adding that the SSL is not verified when you create the AzureMailerApiTransport

It is possible that you can add this in an upcoming update, or better yet let us decide from the Laravel project configuration which options for creating the HTTP client can be used.

![image](https://github.com/hafael/azure-mailer-driver/assets/26976637/bfc727ed-b504-4562-9f80-4e17d6b084b3)

**Comment by hafael** [comment]
I consider this change valid, but I would like to understand this scenario a little more.
1. Is your laravel application under a domain without ssl certificate?
2. Is it in production or is this a development environment concern?
3. Is the message being sent directly to the Azure service domain or is there a proxy mediating this communication?

About the pull request:
I noticed that the structure of the array proposed in the illustrated image and the change made in the README file would guarantee backwards compatibility, and that's great. But I also think that it would not make it very clear to the developer the reason for the "http" entry in the mail driver configuration. I think the "verify_peer" and "verify_host" entries would be more suitable. What do you think?

Thank you for your time on this solution! :)

**Comment by FuriosoJack** [comment]
Thanks for answering,


- The application is not under an SSL domain
- The development environment is a testing
- If you are pointing directly to the AZURE domain

On the "http" entry it could then be called "symfony_client". since using only "verify_peer" and "verify_host" would limit the ability to configure the other options allowed by the symfony API from the Laravel project configuration.

**Comment by hafael** [comment]
Hi @FuriosoJack ,

I have been following your report, and I am still in favor of your propositions. It turns out that the email transport logic that was in this repository was transferred to [symfony/azure-mailer](https://github.com/symfony/azure-mailer) and any pull request that considers this logic must be made there. My suggestion is that you use the implementation algorithm contained in this repository as a reference example for using the mailer driver.
