### ISSUE TITLE
HttpClientInterface is marked as optional, but will fail if not provided

### ISSUE THREAD

**Issue by davidbarratt** [hafael/azure-mailer-driver#7]
In
https://github.com/hafael/azure-mailer-driver/blob/689f71247c09e5e7fab76c8db94c26a7d0c6987a/src/AzureMailerApiTransport.php#L68
the `HttpClientInterface` is marked as optional, but if it is not provided, this line will fail:
https://github.com/hafael/azure-mailer-driver/blob/689f71247c09e5e7fab76c8db94c26a7d0c6987a/src/AzureMailerApiTransport.php#L104

**Comment by hafael** [comment]
A proposed solution was published in the latest release (v0.2.2)
