### ISSUE TITLE
AbstractTransportFactory dependencies are not passed to AzureMailerApiTransport

### ISSUE THREAD

**Issue by davidbarratt** [hafael/azure-mailer-driver#8]
`AzureMailerTransportFactory` extends `AbstractTransportFactory`
https://github.com/hafael/azure-mailer-driver/blob/689f71247c09e5e7fab76c8db94c26a7d0c6987a/src/AzureMailerTransportFactory.php#L10-L10

which has dependencies:
https://github.com/symfony/symfony/blob/60e5f25f78f025bb81ec605f7a6fd664667f9e0e/src/Symfony/Component/Mailer/Transport/AbstractTransportFactory.php#L24-L33

but these dependencies are not passed on to `AzureMailerApiTransport`
https://github.com/hafael/azure-mailer-driver/blob/689f71247c09e5e7fab76c8db94c26a7d0c6987a/src/AzureMailerTransportFactory.php#L21

despite accepting them:
https://github.com/hafael/azure-mailer-driver/blob/689f71247c09e5e7fab76c8db94c26a7d0c6987a/src/AzureMailerApiTransport.php#L68

**Comment by hafael** [comment]
A proposed solution was published in the latest release (v0.2.2)
