### ISSUE TITLE
README states a requirement that is not in composer.json

### ISSUE THREAD

**Issue by davidbarratt** [hafael/azure-mailer-driver#9]
The `README.md` states that [symfony/http-client](https://github.com/symfony/http-client) is a requirement:
https://github.com/hafael/azure-mailer-driver/blob/689f71247c09e5e7fab76c8db94c26a7d0c6987a/README.md?plain=1#L18

Indeed, if the interface is missing, this line will fail
https://github.com/hafael/azure-mailer-driver/blob/689f71247c09e5e7fab76c8db94c26a7d0c6987a/src/AzureMailerApiTransport.php#L104

Since this is a non-optional dependency, it would be better to include [symfony/http-client](https://github.com/symfony/http-client) in the `require` portion of the `composer.json` file
https://github.com/hafael/azure-mailer-driver/blob/689f71247c09e5e7fab76c8db94c26a7d0c6987a/composer.json#L9-L12
even something as broad as `*`, while not being accurate, is better than nothing.

**Comment by hafael** [comment]
A proposed solution was published in the latest release (v0.2.2)
